### PR TITLE
Coding style updates

### PR DESCRIPTION
**Pull request by knutzk**
@maspalla,

Here are the changes that I would like to request you make before accepting KLFitter/KLFitter#100. This will look like _a lot of_ changes, but all of them are only cosmetic:
- Naming of protected/private members starting with `m_`
- Using the `KLFitter::` namespace consistently
- Compatibility of the comments with Doxygen for documentation purposes
- Other minor formatting adjustments (spacing/comments/whitelines)
- I shuffled the order of a couple of functions to match them with the LikelihoodTopLeptonJets class.
- Updated copyright dates for those files that were touched.

Please let me know if any if these changes to your likelihood is not fine with you! We can certainly discuss about them.

### CODE REVIEW

**Comment by knutzk** [comment]
Tagging @TomasDado to let him know about this, too.

**Comment by maspalla** [comment]
Hi,

This likelihood was just copy-pasted from the 2T version, with minimal changes to the logic.

So, year changes are obviously fine and so are the namespace changes.

The comment about single-top production is probably fine too: this was actually developed for ttbar, but it could be used in the context of a single top production (or a t+X, provided that X does not interfere with t).

We don't really know why the variable names have changed. We hope the version of KLFitter on github and the one used in athena are not too different. We don't really have a good way of testing KLFitter standalone ...

Best,
Margherita
(also on behalf of Sven Menke, who's not on gitHub but wrote this part of the code)

**Comment by knutzk** [comment]
Hi @maspalla, thanks for the feedback! I agree with your comment – in the end the likelihood can be used for any final state where one desires to reconstruct one single top quark. I clarified this in the comment in the class header file. 

Probably you (or Sven) based this likelihood off of the all-hadronic ttbar likelihood? Then the names have not 'changed', we just have not updated that likelihood with how we would like the code to look, because it is barely used by anyone. Our benchmark is usually the lepton+jets likelihood, which is the basis for many others. Sorry to insist on these code changes, but with this PR I hope it's not too much work :) Any of the changes in this PR are really just of cosmetic nature, so I don't expect to see any impact on the performance or on the physics.

If you're fine with this PR 'as is', please feel free to hit the merge button below – then KLFitter/KLFitter#100 will update automatically.

Best,
Knut

**Comment by maspalla** [comment]
Hi @knutzk ,
ok, thanks for the adjustments.
Indeed, we copied from the allHad likelihood, so that's why.
Merging. (thank for clarifying this btw, I'n new to gitHub...)
Best,
M.

**Pull request merged**
